#!/usr/bin/env bash
#
# setup.sh — one-shot Layer A onboarding.
#
# Prepares everything needed to run the autonomous triage over a GitHub repo:
#   1. preflight checks (docker, uv, gh)
#   2. python 3.12 venv + deps (via uv)
#   3. collects parameters and writes a Layer A .env (PAT auth path, DRY_RUN on)
#
# Safe to re-run: existing .env is backed up, existing values are offered as
# defaults, and DRY_RUN defaults to 1 so nothing mutates real issues until you
# explicitly go live.
#
# Usage:  bash scripts/setup.sh   (or: make setup)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

bold() { printf '\033[1m%s\033[0m\n' "$1"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$1"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$1"; }
die()  { printf '  \033[31m✗ %s\033[0m\n' "$1" >&2; exit 1; }

bold "Issue Agent — Layer A setup"
echo

# --- 1. Preflight -----------------------------------------------------------
bold "1/3  Preflight"

command -v docker >/dev/null 2>&1 || die "docker not found — install Docker Desktop."
docker info >/dev/null 2>&1 || die "docker is installed but not running — start Docker and re-run."
ok "docker running"

command -v uv >/dev/null 2>&1 || die "uv not found — install: curl -LsSf https://astral.sh/uv/install.sh | sh"
ok "uv present"

command -v gh >/dev/null 2>&1 || die "gh (GitHub CLI) not found — install: https://cli.github.com"
if ! gh auth status >/dev/null 2>&1; then
  die "gh is not authenticated — run 'gh auth login' first (needed to read/label issues)."
fi
ok "gh authenticated ($(gh api user --jq .login 2>/dev/null || echo '?'))"
echo

# --- 2. Python env ----------------------------------------------------------
bold "2/3  Python env (uv, python 3.12)"

if [ ! -x ".venv/bin/python" ]; then
  uv venv --python 3.12 .venv
  ok "created .venv (python 3.12)"
else
  ok ".venv already exists"
fi
uv pip install --quiet --python .venv/bin/python -r worker/requirements.txt -r requirements-dev.txt
ok "dependencies installed"
echo

# --- 3. Parameters ----------------------------------------------------------
bold "3/3  Parameters → .env"

# Read a current value out of an existing .env, if any (for re-runs).
cur() { [ -f .env ] && grep -E "^$1=" .env | head -1 | cut -d= -f2- || true; }

# repo
default_repo="$(cur GITHUB_REPOSITORY)"; default_repo="${default_repo:-kibarik/po-helper}"
read -r -p "  Target GitHub repo [owner/name] (${default_repo}): " REPO
REPO="${REPO:-$default_repo}"

# GH token — offer the one gh already holds
gh_token_auto="$(gh auth token 2>/dev/null || true)"
if [ -n "$gh_token_auto" ]; then
  read -r -p "  Use the token from 'gh auth' for issue read/write? [Y/n]: " use_gh
  if [[ "${use_gh:-Y}" =~ ^[Nn]$ ]]; then
    read -r -s -p "  Paste GitHub token (Issues r/w, Contents r): " GH_TOKEN_VAL; echo
  else
    GH_TOKEN_VAL="$gh_token_auto"
    ok "using gh auth token"
  fi
else
  read -r -s -p "  Paste GitHub token (Issues r/w, Contents r): " GH_TOKEN_VAL; echo
fi
[ -n "$GH_TOKEN_VAL" ] || die "a GitHub token is required."

# z.ai key
cur_zai="$(cur ZAI_API_KEY)"
if [ -n "$cur_zai" ]; then
  read -r -p "  Keep existing ZAI_API_KEY? [Y/n]: " keep_zai
  if [[ "${keep_zai:-Y}" =~ ^[Nn]$ ]]; then
    read -r -s -p "  Paste ZAI_API_KEY: " ZAI_KEY; echo
  else
    ZAI_KEY="$cur_zai"; ok "kept existing ZAI_API_KEY"
  fi
else
  read -r -s -p "  Paste ZAI_API_KEY (z.ai): " ZAI_KEY; echo
fi
[ -n "$ZAI_KEY" ] || die "ZAI_API_KEY is required (all LLM stages use it)."

# defaults (kept from existing .env when present)
ZAI_BASE_URL="$(cur ZAI_BASE_URL)";   ZAI_BASE_URL="${ZAI_BASE_URL:-https://api.z.ai/api/coding/paas/v4}"
ANTHROPIC_BASE_URL="$(cur ANTHROPIC_BASE_URL)"; ANTHROPIC_BASE_URL="${ANTHROPIC_BASE_URL:-https://api.z.ai/api/anthropic}"
MODEL_GATE="$(cur MODEL_GATE)";       MODEL_GATE="${MODEL_GATE:-glm-4.5-air}"
MODEL_CLASSIFY="$(cur MODEL_CLASSIFY)"; MODEL_CLASSIFY="${MODEL_CLASSIFY:-glm-4.6}"
echo

# --- backup + write ---------------------------------------------------------
if [ -f .env ]; then
  bak=".env.bak.$(date +%Y%m%d-%H%M%S)"
  cp .env "$bak"; warn "existing .env backed up to $bak"
fi

cat > .env <<EOF
# Generated by scripts/setup.sh ($(date +%Y-%m-%d)). Layer A (PAT auth, DRY_RUN).
# GitHub App fields left blank on purpose — Layer A uses the PAT path below.

GITHUB_APP_ID=
GITHUB_PRIVATE_KEY_PATH=/app/secrets/github-app-private-key.pem
GITHUB_WEBHOOK_SECRET=unused-in-layer-a
GITHUB_INSTALLATION_ID=
GITHUB_REPOSITORY=${REPO}

# --- GitHub PAT (Layer A) ---
GH_TOKEN=${GH_TOKEN_VAL}

# --- GLM via z.ai ---
ZAI_BASE_URL=${ZAI_BASE_URL}
ZAI_API_KEY=${ZAI_KEY}
ANTHROPIC_BASE_URL=${ANTHROPIC_BASE_URL}
ANTHROPIC_AUTH_TOKEN=

# --- Models ---
MODEL_GATE=${MODEL_GATE}
MODEL_CLASSIFY=${MODEL_CLASSIFY}

# --- Layer A safety: 1 = dry-run (no real comments/labels/closes) ---
DRY_RUN=1
EOF
chmod 600 .env
ok "wrote .env (DRY_RUN=1, repo=${REPO})"
echo

bold "Done. Next steps:"
cat <<'EOF'
  make up          # build & start temporal + worker (first build ~a few min)
  make logs        # watch the worker (Temporal UI: http://localhost:8080)
  make dry-run     # triage ALL open issues in DRY_RUN — nothing is mutated
                   #   (or: make backfill-one issue=<N> for a single smoke test)
  # review the [DRY_RUN] lines in the logs, then:
  make go-live     # flip DRY_RUN off, restart worker, run for real
EOF
